<?php

namespace App\Enums;

enum ChatEnum
{
    const CHAT_IMAGES = "chat_images";

    const CHAT_AUDIOS = "chat_audios";

    const DISTANCE_DURATION_COST_STYLE = "DISTANCE_DURATION_COST_STYLE";

    const ADMIN_WARNING_MESSAGE_STYLE = "ADMIN_WARNING_MESSAGE_STYLE";

    const EXPORT_INVOICE_STYLE = "EXPORT_INVOICE_STYLE";

    const SHARE_LOCATION_STYLE = "SHARE_LOCATION_STYLE";

    const OFFER_FROM_CAPTAIN_STYLE = "OFFER_FROM_CAPTAIN_STYLE";

    const ORDER_PICK_LOCATION_STYLE = "ORDER_PICK_LOCATION_STYLE";

    const ORDER_DROP_OFF_LOCATION_STYLE = "ORDER_DROP_OFF_LOCATION_STYLE";

}
